[config]
version_check = true
caching = false

[config.wallpaper]
command = "hyprpaper"
set = true

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.rasi]
input_path = '~/.config/matugen/templates/colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/colors.conf'
output_path = '~/.config/hypr/colors.conf'
