[config]
version_check = true
caching = false

[config.wallpaper]
command = "hyprpaper"
set = true

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.quickshell]
input_path = '~/.config/matugen/templates/Colors.qml'
output_path = '~/.config/quickshell/states/Colors.qml'

[templates.rasi]
input_path = '~/.config/matugen/templates/colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/colors.conf'
output_path = '~/.config/hypr/colors.conf'
