[config]
version_check = true
caching = false

[config.wallpaper]
command = "hyprpaper"
set = true

[templates.css]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.rasi]
input_path = '~/.config/matugen/templates/colors.rasi'
output_path = '~/.config/rofi/colors.rasi'
