

[pacman]
packages = [
    "alacritty",
    "base",
    "base-devel",
    "bluez",
    "bluez-utils",
    "brightnessctl",
    "cpupower",
    "dnsmasq",
    "docker",
    "docker-buildx",
    "dolphin",
    "dosfstools",
    "efibootmgr",
    "fastfetch",
    "fd",
    "fish",
    "fzf",
    "htop",
    "hypridle",
    "hyprland",
    "hyprlock",
    "hyprpaper",
    "hyprpicker",
    "hyprpolkitagent",
    "hyprshot",
    "imagemagick",
    "kitty",
    "linux",
    "linux-firmware",
    "loupe",
    "man-db",
    "matugen",
    "neovim",
    "networkmanager",
    "npm",
    "openbsd-netcat",
    "os-prober",
    "pacman-contrib",
    "pavucontrol",
    "pipewire-alsa",
    "pipewire-pulse",
    "power-profiles-daemon",
    "python-pip",
    "python-uv",
    "quickshell",
    "rofi",
    "rustup",
    "starship",
    "tree-sitter-cli",
    "ttf-jetbrains-mono",
    "ttf-jetbrains-mono-nerd",
    "unzip",
    "vim",
    "waybar",
    "wget",
    "xdg-desktop-portal-hyprland",
    "zip",
]

[paru]
packages = [
    "popsicle",
    "sddm-silent-theme",
    "zen-browser-bin",
]

[dotfiles]
dirs = [
    "fastfetch",
    "fish",
    "fontconfig",
    "gtk-3.0",
    "gtk-4.0",
    "hypr",
    "kitty",
    "matugen",
    "nvim",
    "quickshell",
    "rofi",
    "starship",
    "waybar",
]

[display_manager]
conf = """
[General]
InputMethod=qtvirtualkeyboard
GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/silent/components/,QT_IM_MODULE=qtvirtualkeyboard

[Theme]
Current=silent
"""
