

[pacman]
packages = [
    "alacritty",
    "android-tools",
    "base",
    "base-devel",
    "blueman",
    "bluez-utils",
    "bridge-utils",
    "brightnessctl",
    "cpupower",
    "docker",
    "docker-buildx",
    "dolphin",
    "dosfstools",
    "efibootmgr",
    "evince",
    "fastfetch",
    "fd",
    "fish",
    "fzf",
    "grub",
    "htop",
    "hypridle",
    "hyprland",
    "hyprlock",
    "hyprpaper",
    "hyprpicker",
    "hyprshot",
    "imagemagick",
    "kdeconnect",
    "kitty",
    "libreoffice-fresh",
    "linux",
    "linux-firmware",
    "loupe",
    "man-db",
    "matugen",
    "neovim",
    "networkmanager",
    "npm",
    "os-prober",
    "pavucontrol",
    "pipewire-alsa",
    "pipewire-pulse",
    "power-profiles-daemon",
    "powertop",
    "proton-vpn-gtk-app",
    "python-pip",
    "qemu-full",
    "rofi",
    "rustup",
    "starship",
    "swaync",
    "ttf-jetbrains-mono",
    "ttf-jetbrains-mono-nerd",
    "unzip",
    "vim",
    "waybar",
    "wget",
    "wofi",
    "xorg-xhost",
    "zip"
]

[paru]
packages = [
    "matugen-bin"
]

[dotfiles]
dirs = [
    "fastfetch",
    "fish",
    "fontconfig",
    "gtk-3.0",
    "gtk-4.0",
    "hellwal",
    "hypr",
    "kitty",
    "matugen",
    "nvim",
    "rofi",
    "starship",
    "swaync",
    "waybar",
    "wofi"
]
